### ISSUE TITLE
Run on custom image?

### ISSUE THREAD

**Issue by PuneetKohli** [baidut/OpenCE#2]
Hi, is there any way (tutorial if possible) to run this on a custom image of our own?

**Comment by baidut** [comment]
```matlab
method = @Ying_2017_ICCV; % or @Ying_2017_CAIP or @amsr or @dheci 
I = imread('yellowlily.jpg');
J = method(I); 
subplot 121; imshow(I); title('Original Image');
subplot 122; imshow(J); title('Enhanced Result');
```

**Comment by PuneetKohli** [comment]
Thanks very much! This works great from within Matlab!

Not an expert with Matlab so a few quick questions-
1. Could you please provide sample code to save the result image to a file

2. How would I be able to run this on a video, instead of an image. In Python, I would do this by using OpenCV and breaking down the video into frames. Could you provide some reference code for the same in Matlab?

3. Would it be possible to use this code as a command line tool? That way I can run it as a blackbox from my existing Python pipeline.

**Comment by baidut** [comment]
@PuneetKohli 
1.  Please type  `doc imwrite` and press enter in Matlab
2.  type  `doc VideoReader` 
3.  https://www.mathworks.com/matlabcentral/answers/102082-how-do-i-call-matlab-from-the-dos-prompt` 

Actually, I'm just planing to re-implement this project using python, hopefully I can finish it soon.
