### ISSUE TITLE
AMSR implementation seems to give strange output

### ISSUE THREAD

**Issue by mss3331** [baidut/OpenCE#3]
Dear Sir:
 Thanks so much for your effort, I am soooo grateful. You are good addition to the knowledge. However, the implementation of AMSR is not correct. I used AMSR.m for the attached image and the result is black image.

Original Image
![park_original](https://user-images.githubusercontent.com/16062814/40873576-76ca89ae-6695-11e8-9bc2-b114e2d4f962.jpg)

AMSR Image
![park_amsr](https://user-images.githubusercontent.com/16062814/40873577-7892a9c4-6695-11e8-84d6-c9743aeb5fab.jpg)

**Comment by baidut** [comment]
@mss3331  Sorry, I don't have time to fix this currently, but you can try my implementation of related retinex-based methods (SSR, MSR and MSRCR) , see https://github.com/baidut/OpenCE/commit/40e1f7f360e3f47dc9fe66c003142a815a70eba7

**Comment by mss3331** [comment]
@baidut  You ARE Great ! Thanks :)
